openapi: 3.0.1
info:
  title: Authenticator JWT
  description: Proyecto SpringBoot con seguridad web para creacion y login de usuarios con tecnologia JWT
  contact:
    name: Vincetl Hernando Guerrero Mendez
    url: https://www.linkedin.com/in/vincetl-guerrero
  version: v1
servers:
  - url: http://Server:Puerto/
    variables: {}
paths:
  /api/v1/auth/signup:
    post:
      tags:
        - auth-controller
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SignupResponse'
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GeneralResponse'
  /api/v1/auth/signin:
    post:
      tags:
        - auth-controller
      operationId: authenticateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SigninResponse'
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GeneralResponse'
  /api/v1/test/auth:
    get:
      tags:
        - test-controller
      operationId: userNoActive
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GeneralResponse'
  /api/v1/test/all:
    get:
      tags:
        - test-controller
      operationId: allAccess
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GeneralResponse'
  /api/v1/test/activo:
    get:
      tags:
        - test-controller
      operationId: userActive
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GeneralResponse'
components:
  schemas:
    LoginRequest:
      required:
        - password
        - username
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    SigninResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        token:
          type: string
        isActive:
          type: boolean
    PhoneDTO:
      required:
        - cityCode
        - countryCode
        - number
      type: object
      properties:
        number:
          type: integer
          format: int32
        cityCode:
          type: integer
          format: int32
        countryCode:
          type: integer
          format: int32
    SignupRequest:
      required:
        - email
        - name
        - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        phones:
          type: array
          items:
            $ref: '#/components/schemas/PhoneDTO'
    SignupResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        created:
          type: string
          format: date-time
        modified:
          type: string
          format: date-time
        lastLogin:
          type: string
          format: date-time
        token:
          type: string
        isActive:
          type: boolean
    GeneralResponse:
      type: object
      properties:
        message:
          type: string